gestformandosMVC/Models/GestFormandos.old/Evaluation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace gestformandosMVC.Models.GestFormandos
{
    public class Evaluation
    {
        [Key]
        public int EvaluationID { get; set; }

        [Display(Name = "Estudante")] [Required(ErrorMessage = "A avaliação necessita de estar associada a um {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "A avaliação necessita de estar associada a um {0}.")]
        public int EvaluationStudentID { get; set; }
        public virtual Student EvaluationStudent { get; set; }

        [Display(Name = "UFCD")] [Required(ErrorMessage = "A avaliação necessita de estar associada a uma {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "A avaliação necessita de estar associada a uma {0}.")]
        public int EvaluationUFCDID { get; set; }
        public virtual UFCD EvaluationUFCD { get; set; }

        [Display(Name = "Avaliação")] [Required(ErrorMessage = "Tem de ter uma {0}.")]
        [Range(0, 20, ErrorMessage = "A {0} consiste de valores entre {1} e {2}.")]
        public double EvaluationGrade { get; set; }

        [Display(Name = "Observações")]
        [StringLength(250, ErrorMessage = "As {0} só podem conter até {1} caractéres.")]
        public string EvaluationDescription { get; set; }
    }
}

gestformandosMVC/Models/GestFormandos.old/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using gestformandosMVC.Helper;

namespace gestformandosMVC.Models.GestFormandos
{
    public class Team
    {
        [Key]
        public int TeamID { get; set; }

        [Display(Name = "Referência")] [Required(ErrorMessage = "A turma necessita de ter uma {0}.")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "A {0} tem de ter entre {2} e {1} caractéres.")]
        public string TeamName { get; set; }

        [Display(Name = "Data de Início")] [DataType(DataType.Date)]
        [Required(ErrorMessage = "A turma tem de ter uma {0}.")]
        public DateTime TeamStartDate { get; set; }

        [Display(Name = "Data de Término")] [DataType(DataType.Date)]
        //[Required(ErrorMessageResourceName = "EndDateReqError", ErrorMessageResourceType = typeof(TeamLoc))]
        public DateTime TeamEndDate { get; set; }

        [Display(Name = "Curso")] [Required(ErrorMessage = "A turma tem de estar associada a um {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Por favor escolha um {0}.")]
        public int TeamCourseID { get; set; }
        public virtual Course TeamCourse { get; set; }
    }
}

gestformandosMVC/ViewModels/Evaluations/GradeableStudentsTeamViewModel.cs
using gestformandosMVC.Data.Entities;
using gestformandosMVC.ViewModels.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gestformandosMVC.ViewModels.Evaluations
{
    public class GradeableStudentsTeamViewModel
    {
        public Team Team { get; set; }

        public Profile ProfileLabel { get; set; }
        public Student StudentLabel { get; set; }
        public Ufcd UfcdLabel { get; set; }


        public List<Student> Students { get; set; }
        public List<UFCDStudentEvalUnitViewModel> StudentEvalsPerUFCD { get; set; }

        public bool IsTeacher { get; set; }

    }
}

gestformandosMVC/ViewModels/Evaluations/StudentWithEvaluationsViewModel.cs
using gestformandosMVC.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gestformandosMVC.ViewModels.Evaluations
{
    public class StudentWithEvaluationsViewModel
    {
        public Profile Student { get; set; }

        public List<Evaluation> Evaluations { get; set; }
    }
}

gestformandosMVC/ViewModels/Teams/TeamDetailsWithUFCDViewModel.cs
using gestformandosMVC.Data.Entities;
using gestformandosMVC.ViewModels.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gestformandosMVC.ViewModels.Teams
{
    public class TeamDetailsWithUFCDViewModel
    {
        public Team Team { get; set; }

        public List<UFCDTeacherUnitViewModel> UfcdTeacher { get; set; }

        public bool IsTeacher { get; set; }
    }
}

gestformandosMVC/ViewModels/Teams/TeamWithStudentsViewModel.cs
using gestformandosMVC.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gestformandosMVC.ViewModels.Teams
{
    public class TeamWithStudentsViewModel
    {
        public Team Team { get; set; }

        public Student StudentLabel { get; set; }
        public Profile ProfileLabel { get; set; }

        public List<Student> Students { get; set; }
    }
}

gestformandosMVC/ViewModels/Teams/TeamWithStudentsWithUFCDViewModel.cs
using gestformandosMVC.ViewModels.Units;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace gestformandosMVC.ViewModels.Teams
{
    public class TeamWithStudentsWithUFCDViewModel : TeamWithStudentsViewModel
    {
        public List<UFCDTeacherUnitViewModel> UfcdTeacher { get; set; }

        public bool IsTeacher { get; set; }
    }
}

gestformandosMVC/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gestformandosMVC.Data.DatabaseContexts;
using gestformandosMVC.Data.Entities;
using gestformandosMVC.Data.Repository;
using gestformandosMVC.ViewModels.Evaluations;
using gestformandosMVC.ViewModels.Units;
using Microsoft.AspNet.Identity;

namespace gestformandosMVC.Controllers
{
    [Authorize]
    public class EvaluationsController : Controller
    {
        private EvaluationRepository evalRepo = new EvaluationRepository();
        private TeamRepository teamRepo = new TeamRepository();
        private UfcdRepository ufcdRepo = new UfcdRepository();
        private HasClassesRepository hasClassesRepo = new HasClassesRepository();
        private ProfileRepository profileRepo = new ProfileRepository();
        private StudentRepository studentRepo = new StudentRepository();

        // GET: Evaluations
        public async Task<ActionResult> Index()
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Evaluations/Team/{id}
        [Authorize(Roles = "SuperUser, Administrativo, Director, Formador")]
        public async Task<ActionResult> Team(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = await teamRepo.GetByIdAsync(id.Value);
            if (team != null)
            {
                List<Student> teamStudents = await teamRepo.GetTeamAllStudentsAsync(id.Value);
                if (teamStudents != null)
                {
                    var evaluationVM = new GradeableStudentsTeamViewModel()
                    {
                        Team = team,
                        Students = teamStudents
                    };

                    evaluationVM.StudentEvalsPerUFCD = new List<UFCDStudentEvalUnitViewModel>();
                    foreach (var ufcd in team.Course.Ufcds)
                    {
                        var ufcdStudentEvals = new UFCDStudentEvalUnitViewModel()
                        {
                            Ufcd = ufcd
                        };

                        ufcdStudentEvals.StudentEvals = new List<StudentEvalUnitViewModel>();
                        foreach (var student in teamStudents)
                        {
                            var studentEval = new StudentEvalUnitViewModel()
                            {
                                Evaluation = evalRepo.GetEvaluationByStudentAndUfcd(student.Id, ufcd.Id),
                                Student = student
                            };

                            ufcdStudentEvals.StudentEvals.Add(studentEval);
                        }

                        var hasClass = hasClassesRepo.GetByTeamIdAndUfcdId(team.Id, ufcd.Id);
                        var profile = await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId());

                        if (hasClass != null)
                        {
                            if (hasClass.Professor.ProfileId == profile.Id)
                            {
                                ufcdStudentEvals.IsTeacher = true;
                                evaluationVM.IsTeacher = true;
                            }
                        }

                        evaluationVM.StudentEvalsPerUFCD.Add(ufcdStudentEvals);
                    }

                    return View(evaluationVM);
                }
            }
            return View();
        }

        // POST: Evaluations/Evaluate?teamID={teamID}&evalID={evalID}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperUser, Administrativo, Director, Formador")]
        public async Task<ActionResult> Evaluate(int teamID, int evalID)
        {
            var evaluation = await evalRepo.GetByIdAsync(evalID);
            if (evaluation != null)
            {
                var gradeString = Request.Form["grade"].Replace('.',',');
                var grade = double.Parse(gradeString);
                var description = Request.Form["description"];

                evaluation.Grade = grade;
                evaluation.Description = description;

                await evalRepo.UpdateAsync(evaluation);

                ViewBag.SuccessMessage = "Avaliação lançada com sucesso";
            }

            // Recreate View
            Team team = await teamRepo.GetByIdAsync(teamID);
            if (team != null)
            {
                List<Student> teamStudents = await teamRepo.GetTeamAllStudentsAsync(teamID);
                if (teamStudents != null)
                {
                    var evaluationVM = new GradeableStudentsTeamViewModel()
                    {
                        Team = team,
                        Students = teamStudents
                    };

                    evaluationVM.StudentEvalsPerUFCD = new List<UFCDStudentEvalUnitViewModel>();
                    foreach (var ufcd in team.Course.Ufcds)
                    {
                        var ufcdStudentEvals = new UFCDStudentEvalUnitViewModel()
                        {
                            Ufcd = ufcd
                        };

                        ufcdStudentEvals.StudentEvals = new List<StudentEvalUnitViewModel>();
                        foreach (var student in teamStudents)
                        {
                            var studentEval = new StudentEvalUnitViewModel()
                            {
                                Evaluation = evalRepo.GetEvaluationByStudentAndUfcd(student.Id, ufcd.Id),
                                Student = student
                            };

                            ufcdStudentEvals.StudentEvals.Add(studentEval);
                        }

                        var hasClass = hasClassesRepo.GetByTeamIdAndUfcdId(team.Id, ufcd.Id);
                        var profile = await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId());

                        if (hasClass != null)
                        {
                            if (hasClass.Professor.ProfileId == profile.Id)
                            {
                                ufcdStudentEvals.IsTeacher = true;
                                evaluationVM.IsTeacher = true;
                            }
                        }

                        evaluationVM.StudentEvalsPerUFCD.Add(ufcdStudentEvals);
                    }

                    return View("Team", evaluationVM);
                }
            }

            return HttpNotFound();
        }

        // POST: Evaluations/Evaluate?teamID={teamID}&studentID={studentID}&ufcdID={ufcdID}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperUser, Administrativo, Director, Formador")]
        public async Task<ActionResult> EvaluateNew(int teamID, int studentID, int ufcdID)
        {
            var grade = double.Parse(Request.Form["grade"].Replace('.',','));
            var description = Request.Form["description"];

            var evaluation = new Evaluation()
            {
                StudentId = studentID,
                UfcdId = ufcdID,
                Grade = grade,
                Description = Request.Form["description"]
            };

            await evalRepo.AddAsync(evaluation);

            // Recreate View
            Team team = await teamRepo.GetByIdAsync(teamID);
            if (team != null)
            {
                List<Student> teamStudents = await teamRepo.GetTeamAllStudentsAsync(teamID);
                if (teamStudents != null)
                {
                    var evaluationVM = new GradeableStudentsTeamViewModel()
                    {
                        Team = team,
                        Students = teamStudents
                    };

                    evaluationVM.StudentEvalsPerUFCD = new List<UFCDStudentEvalUnitViewModel>();
                    foreach (var ufcd in team.Course.Ufcds)
                    {
                        var ufcdStudentEvals = new UFCDStudentEvalUnitViewModel()
                        {
                            Ufcd = ufcd
                        };

                        ufcdStudentEvals.StudentEvals = new List<StudentEvalUnitViewModel>();
                        foreach (var student in teamStudents)
                        {
                            var studentEval = new StudentEvalUnitViewModel()
                            {
                                Evaluation = evalRepo.GetEvaluationByStudentAndUfcd(student.Id, ufcd.Id),
                                Student = student
                            };

                            ufcdStudentEvals.StudentEvals.Add(studentEval);
                        }

                        var hasClass = hasClassesRepo.GetByTeamIdAndUfcdId(team.Id, ufcd.Id);
                        var profile = await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId());

                        if (hasClass != null)
                        {
                            if (hasClass.Professor.ProfileId == profile.Id)
                            {
                                ufcdStudentEvals.IsTeacher = true;
                                evaluationVM.IsTeacher = true;
                            }
                        }

                        evaluationVM.StudentEvalsPerUFCD.Add(ufcdStudentEvals);
                    }

                    return View("Team", evaluationVM);
                }
            }

            return HttpNotFound();
        }

        // GET: /Evaluations/Me
        [Authorize(Roles = "Estudante")]
        public async Task<ActionResult> Me()
        {
            var currentProfile = await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId());
            if (currentProfile == null)

gestformandosMVC/Views/Evaluations/Details.cshtml
@model gestformandosMVC.ViewModels.Evaluations.StudentWithEvaluationsViewModel
@{
    ViewBag.Title = "Avaliações";
}

<h2>@Model.Student.FullName</h2>
<h4>Avaliações</h4>
<br/>
<div class="row" id="search-bar">
    <div class="col-sm-3 col-md-2">
        <p>Pesquisar:</p>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="text" />
    </div>

</div>
<div>
    <div class="table-responsive table-card">
        <table class="table">
            <tr>
                <th>
                    Referência
                </th>
                <th>
                    UFCD
                </th>
                <th>
                    Nota
                </th>
                <th></th>
            </tr>
            <tr class="table-spacing"></tr>
            @foreach (var item in Model.Evaluations)
            {
                <tr>
                    <td>
                        @item.Ufcd.Reference
                    </td>
                    <td>
                        @item.Ufcd.Name
                    </td>
                    <td title="@item.Description">
                        @item.Grade
                    </td>
                    <td></td>
                </tr>
                <tr class="table-spacing"></tr>
            }
        </table>
    </div>
</div>
<script type="text/javascript">
    document.querySelector('#search-bar input').addEventListener('input', (e) => {
        let tableRows = document.querySelectorAll('tr:not(:first-child):not(.table-spacing)');

        search(tableRows, e.target.value);
    });

    function search(elements, text) {
        for (let element of elements) {
            let txtValue = element.innerText;

            if (txtValue.toUpperCase().indexOf(text.toUpperCase()) > -1) {
                element.style.display = "";
                element.nextSibling.nextSibling.style.display = "";
            } else {
                element.style.display = "none";
                element.nextSibling.nextSibling.style.display = "none";
            }
        }
    }
</script>

gestformandosMVC/Views/Evaluations/Team.cshtml
@model gestformandosMVC.ViewModels.Evaluations.GradeableStudentsTeamViewModel
@{
    ViewBag.Title = "Team";
}

@{
    if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <p><div class="card card-body"><span class="text-danger">@ViewBag.ErrorMessage</span></div></p>
    }
    if (!String.IsNullOrEmpty(ViewBag.SuccessMessage))
    {
        <p><div class="card card-body"><span class="text-success">@ViewBag.SuccessMessage</span></div></p>
    }
}


<h2>@Model.Team.Name</h2>
<h4>Avaliações</h4>

<div class="table-responsive">
    <table class="table table-individual-cells">
        <tr>
            <th>

            </th>
            @foreach (var ufcd in Model.StudentEvalsPerUFCD)
            {
                <th>
                    @ufcd.Ufcd.Name
                </th>
            }
        </tr>
        @{
            foreach (var student in Model.Students)
            {
                <td>
                    @student.Profile.FullName
                </td>
                foreach (var ufcds in Model.StudentEvalsPerUFCD)
                {
                    var evaluation = ufcds.StudentEvals.Find(x => x.Student == student && x.Evaluation?.UfcdId == ufcds.Ufcd.Id);
                    if (evaluation != null)
                    {
                        <td data-toggle="modal"
                            data-target="evalModal"
                            data-evalId="@evaluation.Evaluation.Id"
                            data-ufcdId="@ufcds.Ufcd.Id"
                            data-studentId="@evaluation.Student.Id"
                            data-grade="@evaluation.Evaluation.Grade.ToString().Replace(',','.')"
                            data-description="@evaluation.Evaluation.Description">
                            @evaluation.Evaluation.Grade
                        </td>
                    }
                    else
                    {
                        <td data-toggle="modal"
                            data-target="evalModal"
                            data-evalId="new"
                            data-ufcdId="@ufcds.Ufcd.Id"
                            data-studentId="@student.Id"
                            data-grade="0">
                            N/A
                        </td>
                    }
                }
            }
        }
    </table>
</div>

<div class="modal fade" id="evalModal" aria-labelledby="ModalEval" aria-hidden="true" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Avaliação</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Html.BeginForm("Evaluate", ViewContext.RouteData.Values["controller"].ToString(), FormMethod.Post, new { id = "evalModalForm", @class = "" }))
            {
                @Html.AntiForgeryToken()

                <div class="modal-body">
                    <div class="row form-group">
                        <div class="col-md-12 form-group">
                            <input type="number" min="0" max="20" step="0.1" name="grade" id="modal-grade" value="0" class="form-control text-center" />
                        </div>
                        <div class="col-md-12 form-group">
                            <textarea id="modal-description" name="description" class="form-control"></textarea>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">

                    <input type="submit" id="confirmEval" class="btn btn-primary" value="Submeter" />

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
            }
        </div>
    </div>
</div>


<script type="text/javascript">

    // On showing modal
    $('td[data-evalId]').on('click', function (e) {
        if (e.target.dataset.evalid === 'new') {
            document.querySelector('#evalModal input[name="grade"]').value = "0";
            document.querySelector('#evalModal textarea[name="description"]').value = "";

            $('#evalModal form').attr('action', `@Url.Action("EvaluateNew", "Evaluations", new { teamId = Model.Team.Id })&studentId=${e.target.dataset.studentid}&ufcdId=${e.target.dataset.ufcdid}`);
        } else {
            document.querySelector('#evalModal input[name="grade"]').value = e.target.dataset.grade;
            document.querySelector('#evalModal textarea[name="description"]').value = e.target.dataset.description;

            $('#evalModal form').attr('action', `@Url.Action("Evaluate", "Evaluations", new { teamId = Model.Team.Id })&evalID=${e.target.dataset.evalid}`);
        }

        $('#evalModal').modal('show');
    });
</script>