gestformandosMVC/Models/GestFormandos.old/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using gestformandosMVC.Helper;

namespace gestformandosMVC.Models.GestFormandos
{
    public class Professor
    {
        [Key]
        public int ProfessorID { get; set; }

        [Display(Name = "Primeiro Nome")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [StringLength(40, ErrorMessage = "O {0} deverá conter entre {2} e {1} caractéres.")]
        public string ProfessorFirstName { get; set; }

        [Display(Name = "Apelido")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [StringLength(40, ErrorMessage = "O {0} deverá ter entre {2} e {1} caractéres.")]
        public string ProfessorLastName { get; set; }

        [Display(Name = "Nome Completo")] [NotMapped]
        public virtual string ProfessorFullName
        {
            get { return $"{ProfessorFirstName} {ProfessorLastName}"; }
        }

        [Display(Name = "Género")] [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher um {0}.")]
        [Required(ErrorMessage = "Tem que escolher um {0}.")]
        public int ProfessorGenderID { get; set; }
        public virtual Gender ProfessorGender { get; set; }

        [Display(Name = "Data de Nascimento")] [Required(ErrorMessage = "Tem que inserir uma {0}.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)] [DataType(DataType.Date)]
        [DateTimeOfAgeRange(ErrorMessage = "O aluno tem de ser maior de idade.")]
        public DateTime ProfessorBirthDate { get; set; }

        [Display(Name = "NIF")] [Required(ErrorMessage = "Tem que inserir um {0}")]
        [RegularExpression("^[1-35][0-9]{8,}$", ErrorMessage = "Por favor insira um {0} válido.")]
        public string ProfessorVatNumber { get; set; }

        [Display(Name = "Local de Nascimento")] [Required(ErrorMessage = "O {0} deverá ter entre {2} e {1} caractéres.")]
        [StringLength(40, ErrorMessage = "Tem que inserir um {0}.")]
        public string ProfessorBirthplace { get; set; }

        [Display(Name = "Nacionalidade")] [Required(ErrorMessage = "Tem que escolher uma {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher uma {0}.")] [ForeignKey("ProfessorNationality")]
        public int ProfessorNationalityID { get; set; }
        public virtual Country ProfessorNationality { get; set; }

        [Display(Name = "Cidadania")] [Required(ErrorMessage = "Tem que escolher uma {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher uma {0}.")] [ForeignKey("ProfessorCitizenship")]
        public int ProfessorCitizenshipID { get; set; }
        public virtual Country ProfessorCitizenship { get; set; }

        [Display(Name = "Tipo de Documento")] [Required(ErrorMessage = "Tem que escolher um {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher um {0}.")]
        public int ProfessorDocumentTypeID { get; set; }
        public virtual DocumentType ProfessorDocumentType { get; set; }

        [Display(Name = "Número do Documento")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [RegularExpression("^[0-9]{9,}$", ErrorMessage = "Por favor insira um {0} válido.")]
        [StringLength(30, ErrorMessage = "O {0} tem de ter entre {2} e {1} caractéres.")]
        public string ProfessorDocumentNumber { get; set; }

        [Display(Name = "Data de Emissão")] [DataType(DataType.Date)]
        [Required(ErrorMessage = "Por favor escolha a {0} do documento.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ProfessorDocumentEmissionDate { get; set; }

        [Display(Name = "Data de Validade")] [DataType(DataType.Date)]
        [Required(ErrorMessage = "Por favor escolha a {0} do documento.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime ProfessorDocumentExpirationDate { get; set; }
    }
}

gestformandosMVC/Models/GestFormandos.old/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using gestformandosMVC.Helper;

namespace gestformandosMVC.Models.GestFormandos
{
    public class Student
    {
        [Key]
        public int StudentID { get; set; }

        [Display(Name = "Primeiro Nome")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [StringLength(40, ErrorMessage = "O {0} deverá conter entre {2} e {1} caractéres.")]
        public string StudentFirstName { get; set; }

        [Display(Name = "Apelido")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [StringLength(40, ErrorMessage = "O {0} deverá ter entre {2} e {1} caractéres.")]
        public string StudentLastName { get; set; }

        [Display(Name = "Nome Completo")] [NotMapped]
        public virtual string StudentFullName
        {
            get { return $"{StudentFirstName} {StudentLastName}"; }
        }

        [Display(Name = "Género")] [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher um {0}.")]
        [Required(ErrorMessage = "Tem que escolher um {0}.")]
        public int StudentGenderID { get; set; }
        public virtual Gender StudentGender { get; set; }

        [Display(Name = "Data de Nascimento")] [Required(ErrorMessage = "Tem que inserir uma {0}.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)] [DataType(DataType.Date)]
        [DateTimeOfAgeRange(ErrorMessage = "O aluno tem de ser maior de idade.")]
        public DateTime StudentBirthDate { get; set; }

        [Display(Name = "NIF")] [Required(ErrorMessage = "Tem que inserir um {0}")]
        [RegularExpression("^[1-35][0-9]{8,}$", ErrorMessage = "Por favor insira um {0} válido.")]
        public string StudentVatNumber { get; set; }

        [Display(Name = "Local de Nascimento")] [Required(ErrorMessage = "O {0} deverá ter entre {2} e {1} caractéres.")]
        [StringLength(40, ErrorMessage = "Tem que inserir um {0}.")]
        public string StudentBirthplace { get; set; }

        [Display(Name = "Nacionalidade")] [Required(ErrorMessage = "Tem que escolher uma {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher uma {0}.")] [ForeignKey("StudentNationality")]
        public int StudentNationalityID { get; set; }
        public virtual Country StudentNationality { get; set; }

        [Display(Name = "Cidadania")] [Required(ErrorMessage = "Tem que escolher uma {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher uma {0}.")] [ForeignKey("StudentCitizenship")]
        public int StudentCitizenshipID { get; set; }
        public virtual Country StudentCitizenship { get; set; }

        [Display(Name = "Tipo de Documento")] [Required(ErrorMessage = "Tem que escolher um {0}.")]
        [Range(1, int.MaxValue, ErrorMessage = "Tem que escolher um {0}.")]
        public int StudentDocumentTypeID { get; set; }
        public virtual DocumentType StudentDocumentType { get; set; }

        [Display(Name = "Número do Documento")] [Required(ErrorMessage = "Tem que inserir um {0}.")]
        [RegularExpression("^[0-9]{9,}$", ErrorMessage = "Por favor insira um {0} válido.")]
        [StringLength(30, ErrorMessage = "O {0} tem de ter entre {2} e {1} caractéres.")]
        public string StudentDocumentNumber { get; set; }

        [Display(Name = "Data de Emissão")] [DataType(DataType.Date)]
        [Required(ErrorMessage = "Por favor escolha a {0} do documento.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StudentDocumentEmissionDate { get; set; }

        [Display(Name = "Data de Validade")] [DataType(DataType.Date)]
        [Required(ErrorMessage = "Por favor escolha a {0} do documento.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StudentDocumentExpirationDate { get; set; }

        public virtual ICollection<Evaluation> StudentEvaluations { get; set; }
    }
}

gestformandosMVC/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using gestformandosMVC.Data.DatabaseContexts;
using gestformandosMVC.Data.Entities;
using gestformandosMVC.Data.Repository;
using gestformandosMVC.ViewModels;
using Microsoft.AspNet.Identity;
using gestformandosMVC.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace gestformandosMVC.Controllers
{
    [Authorize]
    public class ProfilesController : Controller
    {
        private ProfileRepository profileRepo = new ProfileRepository();

        // GET: Profiles
        public async Task<ActionResult> Index()
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Profiles/{id}
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var profile = await profileRepo.GetByIdAsync(id.Value);
            if (profile != null)
            {
                ProfileViewModel profileViewModel;

                if (profile != await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId()))
                {
                    if (!User.IsInRole("Administrativo") &&
                    !User.IsInRole("Director") &&
                    !User.IsInRole("SuperUser"))
                    {
                        return RedirectToAction("Me");
                    }

                    profileViewModel = new ProfileViewModel()
                    {
                        Profile = profile,
                        IsSelf = false,
                        ProfessorActive = false,
                        StudentActive = false,
                        AdministrationActive = false
                    };
                }
                else
                {
                    profileViewModel = new ProfileViewModel()
                    {
                        Profile = profile,
                        IsSelf = true,
                        ProfessorActive = false,
                        StudentActive = false,
                        AdministrationActive = false
                    };
                }

                using (GestFormandosDataContext userAuth = new GestFormandosDataContext())
                {
                    var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(userAuth));

                    var activeRoles = userManager.GetRoles(profile.UserId);
                    if (activeRoles.Contains("Administrativo"))
                    {
                        profileViewModel.AdministrationActive = true;
                    }
                    if (activeRoles.Contains("Formador"))
                    {
                        profileViewModel.ProfessorActive = true;
                    }
                    if (activeRoles.Contains("Estudante"))
                    {
                        profileViewModel.StudentActive = true;
                    }

                    return View(profileViewModel);
                }
                    
            }

            return HttpNotFound();
        }

        // GET: Profiles/Me
        public async Task<ActionResult> Me()
        {
            if (User.IsInRole("SuperUser"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var profile = await profileRepo.GetProfileByUserIDAsync(User.Identity.GetUserId());
            if (profile != null)
            {
                var profileViewModel = new ProfileViewModel()
                {
                    Profile = profile,
                    IsSelf = true
                };

                return View("Details", profileViewModel);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        // GET: Profiles/Teaching
        public async Task<ActionResult> Teaching(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var professorRepo = new ProfessorRepository())
            {
                var professor = professorRepo.GetById(id.Value);
                if (professor != null)
                {
                    var viewModel = new ProfessorTeachesViewModel()
                    {
                        FullName = professor.Profile.FullName,
                        Professor = professor,
                        ProfessorCurrentUFCDs = professor.UFCDs.ToList()
                    };

                    return View(viewModel);
                }

                return HttpNotFound();
            }
        }

        // GET: Profiles/Teaches
        [Authorize(Roles = "Administrativo, SuperUser, Director")]
        public async Task<ActionResult> Teaches(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var professorRepo = new ProfessorRepository())
            {
                var professor = professorRepo.GetById(id.Value);
                if (professor != null)
                {
                    var viewModel = new ProfessorTeachesViewModel()
                    {
                        FullName = professor.Profile.FullName,
                        Professor = professor,
                        ProfessorCurrentUFCDs = professor.UFCDs.ToList()
                    };

                    using (var ufcdRepo = new UfcdRepository())
                    {
                        ViewBag.UFCDList = await ufcdRepo.GetListAsync();

                        return View(viewModel);
                    }
                }

                return HttpNotFound();
            }
        }

        // POST: Profiles/Teaches
        [Authorize(Roles = "Administrativo, SuperUser, Director")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Teaches(int id)
        {
            using (var professorRepo = new ProfessorRepository())
            {
                var professor = await professorRepo.GetByIdAsync(id);
                if (professor != null)
                {
                    var ufcds = Request.Form["Ufcds"];
                    if (ufcds != null)
                    {
                        var ufcdIds = ufcds.Split(',');

                        if (await professorRepo.UpdateWithUFCDsAsync(professor, ufcdIds))
                        {
                            ViewBag.SuccessMessage = "UFCDs leccionadas alteradas com sucesso!";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "UFCDs leccionadas alteradas sem sucesso!";
                        }
                    }
                    else
                    {
                        if (await professorRepo.UpdateWithUFCDsAsync(professor, new string[] { }))
                        {
                            ViewBag.SuccessMessage = "UFCDs leccionadas alteradas com sucesso!";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = "UFCDs leccionadas alteradas sem sucesso!";
                        }
                    }

                    var viewModel = new ProfessorTeachesViewModel()
                    {
                        FullName = professor.Profile.FullName,
                        Professor = professor,
                        ProfessorCurrentUFCDs = professor.UFCDs.ToList()
                    };

                    using (var ufcdRepo = new UfcdRepository())
                    {
                        ViewBag.UFCDList = await ufcdRepo.GetListAsync();

                        return View(viewModel);
                    }
                }

                return HttpNotFound();
            }
        }

        // GET: Professors
        [Authorize(Roles = "Administrativo, SuperUser, Director")]
        public async Task<ActionResult> Professors()
        {
            return View(await profileRepo.GetProfileOfProfessorsAsync());
        }

        // GET: Students
        [Authorize(Roles = "Administrativo, SuperUser, Director")]
        public async Task<ActionResult> Students()
        {
            return View(await profileRepo.GetProfileOfStudentsAsync());
        }

        // GET: Administration
        [Authorize(Roles = "Administrativo, SuperUser, Director")]
        public async Task<ActionResult> Admin()
        {
            return View(await profileRepo.GetProfileOfAdminAsync());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                profileRepo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

gestformandosMVC/Views/Profiles/Admin.cshtml
@model IEnumerable<gestformandosMVC.Data.Entities.Profile>
@{
    ViewBag.Title = "Lista de Administrativos";
}

<h2>Lista de Administrativos</h2>
<div class="row" id="search-bar">
    <div class="col-sm-3 col-md-2">
        <p>Pesquisar:</p>
    </div>
    <div class="col-sm-9 col-md-10">
        <input type="text" />
    </div>
</div>
<div class="table-responsive table-card">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>

            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionIcon("info-circle", "Details", "Detalhes", new { id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
            <tr class="table-spacing"></tr>
        }
    </table>
</div>

<script type="text/javascript">
    document.querySelector('#search-bar input').addEventListener('input', (e) => {
        let tableRows = document.querySelectorAll('tr:not(:first-child):not(.table-spacing)');

        search(tableRows, e.target.value);
    });

    function search(elements, text) {
        for (let element of elements) {
            let txtValue = element.innerText;

            if (txtValue.toUpperCase().indexOf(text.toUpperCase()) > -1) {
                element.style.display = "";
            } else {
                element.style.display = "none";
            }
        }
    }
</script>

gestformandosMVC/Views/Profiles/Details.cshtml
@model gestformandosMVC.ViewModels.ProfileViewModel
@{
    ViewBag.Title = "Perfil";
}



<div>
    <div class="row">
        <div class="col-md-6">
            <h2>@Model.Profile.FullName</h2>
            <h4>Perfil</h4>
        </div>
        <div class="col-md-6 text-md-right align-self-center">
            @if (Model.Student != null)
            {
                if (!User.IsInRole("Estudante"))
                {
                    @Html.ActionIcon("user-graduate", "Details", "Avaliação", new { id = Model.Student.Id, controller = "Evaluations" }, new { @class = "btn btn-primary" }, true)
                }
                else if (Model.IsSelf)
                {
                    @Html.ActionIcon("user-graduate", "Me", "Avaliação", new { controller = "Evaluations" }, new { @class = "btn btn-primary" }, true)
                }
            }
            @if (Model.Professor != null)
            {
                if (Model.ProfessorActive)
                {
                    if (User.IsInRole("Director") || User.IsInRole("Administrativo") || User.IsInRole("SuperUser"))
                    {
                        @Html.ActionIcon("chalkboard-teacher", "Teaches", "UFCDs", new { id = Model.Professor.Id }, new { @class = "btn btn-primary" }, true)
                    }
                    else
                    {
                        if (User.Identity.IsAuthenticated)
                        {
                            @Html.ActionIcon("chalkboard-teacher", "Teaching", "UFCDs", new { id = Model.Professor.Id }, new { @class = "btn btn-primary" }, true)
                        }
                    }
                }
            }
        </div>
    </div>
    
    <hr />
    <div class="row">
        <div class="col-md-4">
            @if (Model.Administration != null)
            {
                <dt>@Html.DisplayNameFor(model => model.Administration.Id)</dt>
                <dd>@Html.DisplayFor(model => model.Administration.Id)</dd>
            }
        </div>
        <div class="col-md-4">
            @if (Model.Professor != null)
            {
                <dt>@Html.DisplayNameFor(model => model.Professor.Id)</dt>
                <dd>@Html.DisplayFor(model => model.Professor.Id)</dd>
            }
        </div>
        <div class="col-md-4">
            @if (Model.Student != null)
            {
                <dt>@Html.DisplayNameFor(model => model.Student.Id)</dt>
                <dd>@Html.DisplayFor(model => model.Student.Id)</dd>
            }
        </div>
    </div>
    @if (Model.Administration != null || Model.Professor != null || Model.Student != null)
    {
        <hr />
    }

<div class="card card-body">
    @{
        if (!string.IsNullOrEmpty(Model.Profile.ImagePath))
        {
        <div class="row">
                <div class="col-md-12 text-center">
                    <img src="@Model.Profile.ImagePath" class="img-responsive" id="imagePreview" />
                </div>
        </div>
        <hr/>
        }
    }
    
    <div class="row">
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(model => model.Profile.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Profile.FirstName)
            </dd>
        </div>
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(model => model.Profile.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Profile.LastName)
            </dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(model => model.Profile.Email)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Email)
            </dd>
        </div>
        <div class="col-md-3">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.GenderId)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Gender.Name)
            </dd>
        </div>
        <div class="col-md-3">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.VatNumber)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.VatNumber)
            </dd>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.Birthdate)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Birthdate)
            </dd>
        </div>
        <div class="offset-md-2 col-md-4">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.Birthplace)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Birthplace)
            </dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.CitizenshipId)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Citizenship.Citizenship)
            </dd>
        </div>
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.NationalityId)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.Nationality.Nationality)
            </dd>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.DocumentTypeId)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.DocumentType.Name)
            </dd>
        </div>
        <div class="col-md-8">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.DocumentNumber)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.DocumentNumber)
            </dd>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.DocumentEmissionDate)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.DocumentEmissionDate)
            </dd>
        </div>
        <div class="col-md-6">
            <dt class="border-bottom pb-1">
                @Html.DisplayNameFor(m => m.Profile.DocumentExpirationDate)
            </dt>
            <dd>
                @Html.DisplayFor(m => m.Profile.DocumentExpirationDate)
            </dd>
        </div>
    </div>
</div>
</div>

gestformandosMVC/Views/Profiles/Teaches.cshtml
@model gestformandosMVC.ViewModels.ProfessorTeachesViewModel
@{
    ViewBag.Title = "Ensina...";
}

@{
    if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <p><div class="card card-body"><span class="text-danger">@ViewBag.ErrorMessage</span></div></p>
    }
    if (!String.IsNullOrEmpty(ViewBag.SuccessMessage))
    {
        <p><div class="card card-body"><span class="text-success">@ViewBag.SuccessMessage</span></div></p>
    }
}

<h2>Ensina...</h2>
<div class="row">
    <div class="col-md-6">
        <h4>@Model.FullName</h4>
    </div>
</div>
<br />
@using (Html.BeginForm("Teaches", "Profiles", new { id = Model.Professor.Id }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row form-group">
        <div class="col-md-12">
            <div class="row" id="search-bar">
                <div class="col-md-4">
                    <label for="Ufcds" class="control-label">UFCDs</label>
                </div>
                <div class="col-md-8 row pr-0">
                    <div class="col-3">
                        <p>Pesquisar:</p>
                    </div>
                    <div class="col-9 pr-0">
                        <input type="text" class="form-control" />
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-12">
            <select id="Ufcds" name="Ufcds" class="form-control" multiple="multiple">
                @foreach (var ufcd in ViewBag.UFCDList)
                {
                    if (Model.ProfessorCurrentUFCDs.Any(i => i.Id == ufcd.Id))
                    {
                        <option value="@ufcd.Id" selected>@ufcd.Reference - @ufcd.Name</option>
                    }
                    else
                    {
                        <option value="@ufcd.Id">@ufcd.Reference - @ufcd.Name</option>
                    }
                }
            </select>
        </div>
    </div>
    <div class="form-group" id="form-controls">
        <div class="col-md-12 d-md-inline-flex">
            <div class="col-12 col-md-6">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
            <div class="col-12 col-md-6 text-md-right">
                @Html.ActionLink("Voltar", "Details", new { id = Model.Professor.ProfileId }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    document.querySelector('#search-bar input').addEventListener('input', (e) => {
        let tableRows = document.querySelectorAll('select#Ufcds option');

        search(tableRows, e.target.value);
    });

    function search(elements, text) {
        for (let element of elements) {
            let txtValue = element.innerText;

            if (txtValue.toUpperCase().indexOf(text.toUpperCase()) > -1) {
                element.style.display = "";
                //element.nextSibling.nextSibling.style.display = "";
            } else {
                element.style.display = "none";
                //element.nextSibling.nextSibling.style.display = "none";
            }
        }
    }
</script>

gestformandosMVC/Views/Profiles/Teaching.cshtml
@model gestformandosMVC.ViewModels.ProfessorTeachesViewModel
@{
    ViewBag.Title = "Ensina...";
}

@{
    if (!String.IsNullOrEmpty(ViewBag.ErrorMessage))
    {
        <p><div class="card card-body"><span class="text-danger">@ViewBag.ErrorMessage</span></div></p>
    }
    if (!String.IsNullOrEmpty(ViewBag.SuccessMessage))
    {
        <p><div class="card card-body"><span class="text-success">@ViewBag.SuccessMessage</span></div></p>
    }
}

<h2>Ensina...</h2>
<div class="row">
    <div class="col-md-6">
        <h4>@Model.FullName</h4>
    </div>
</div>
<br />
@using (Html.BeginForm("Teaches", "Profiles", new { id = Model.Professor.Id }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="table-card table-responsive">
        <table class="table">
            <tr>
                <th>UFCD</th>
                <th></th>
            </tr>
            <tr class="table-spacing"></tr>
            @foreach (var ufcd in Model.ProfessorCurrentUFCDs)
            {
                <tr>
                    <td>@ufcd.Reference - @ufcd.Name</td>
                    <td></td>
                </tr>
                <tr class="table-spacing"></tr>
            }
        </table>
    </div>
    <div class="form-group" id="form-controls">
        <div class="col-md-12 d-md-inline-flex">
            <div class="col-12 text-md-right">
                @Html.ActionLink("Voltar", "Details", new { id = Model.Professor.ProfileId }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}